import { Poppins, Pathway_Gothic_One } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Chatbot from "./components/Chatbot";

// Configure Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

// Configure Pathway Gothic One font
const pathwayGothicOne = Pathway_Gothic_One({
  subsets: ["latin"],
  weight: ["400"], // Pathway Gothic One supports only 400 weight
  variable: "--font-pathway-gothic-one",
});

export const metadata = {
  title: "iappsdata",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.png" sizes="32x32" />
      </head>
      <body
        className={`${poppins.variable} ${pathwayGothicOne.variable} bg-themeBG antialiased`}
      >
       
        <Suspense fallback="LOADING .....">
          <Navbar />
          {children}
          <Footer />
        </Suspense>
        <Chatbot />
      </body>
    </html>
  );
}
