import Home from "./services/home/page";

export const metadata = {
  title: "iappsdata",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <>
      <Home />
    </>
  );
}
