import Home from "./(pages)/home/page";


export const metadata = {
  title: "iappsdata",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <>
    <Home/>
    </>
  );
}
